import { Product } from './types';

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: 'np-01',
    name: 'Aceite Esencial de Lavanda Francesa',
    description: '100% puro y quimiotipado. Inductor natural del sueño, relajante del sistema nervioso y calmante cutáneo.',
    category: 'Aceites esenciales',
    priceBs: 480.00,
    priceUsd: 13.15,
    image: 'https://images.unsplash.com/photo-1608571423902-eed4a5ad8108?auto=format&fit=crop&w=600&q=80',
    stock: 24,
    badge: '100% Puro',
    rating: 4.9,
    presentation: 'Frasco ámbar con gotero de 15ml',
    ingredients: 'Lavandula angustifolia 100% destilada al vapor.',
    benefits: ['Reduce el estrés y la ansiedad', 'Mejora la calidad del descanso', 'Alivia picaduras leves'],
    usage: 'Difundir 4-6 gotas en ambiente o diluir 2 gotas en aceite portador para masaje nocturno.'
  },
  {
    id: 'np-02',
    name: 'Citrato de Magnesio + Zinc Bioactivo',
    description: 'Alta biodisponibilidad para la relajación muscular, equilibrio electrolítico y vitalidad metabólica diaria.',
    category: 'Suplementos',
    priceBs: 650.00,
    priceUsd: 17.80,
    image: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&w=600&q=80',
    stock: 45,
    badge: 'Bestseller',
    rating: 5.0,
    presentation: 'Pomo de 120 cápsulas vegetales',
    ingredients: 'Citrato de magnesio elemental puro 400mg, Bisglicinato de zinc 15mg, cápsula de celulosa vegetal.',
    benefits: ['Evita calambres musculares', 'Favorece el descanso reparador', 'Refuerza el sistema inmunológico'],
    usage: 'Tomar 2 cápsulas diarias preferentemente 30 minutos antes de acostarse.'
  },
  {
    id: 'np-03',
    name: 'Sérum Facial Botánico de Rosa Mosqueta y Bakuchiol',
    description: 'Alternativa natural al retinol. Regenerador celular nocturno que unifica el tono e hidrata profundamente.',
    category: 'Cosmética natural',
    priceBs: 720.00,
    priceUsd: 19.72,
    image: 'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?auto=format&fit=crop&w=600&q=80',
    stock: 18,
    badge: 'Vegano',
    rating: 4.8,
    presentation: 'Frasco de vidrio esmerilado de 30ml',
    ingredients: 'Aceite de Rosa Canina prensado en frío, Bakuchiol al 1%, Vitamina E tocoferol y Escualano vegetal.',
    benefits: ['Atenúa líneas de expresión', 'Regenera marcas y manchas solares', 'Nutrición sin residuo graso'],
    usage: 'Aplicar 3-4 gotas sobre rostro y cuello limpios con suaves toques ascendentes.'
  },
  {
    id: 'np-04',
    name: 'Infusión Serenidad Botánica',
    description: 'Mezcla artesanal de manzanilla silvestre, pasiflora, melisa y flores de azahar de cultivo ecológico.',
    category: 'Tés e infusiones',
    priceBs: 290.00,
    priceUsd: 7.95,
    image: 'https://images.unsplash.com/photo-1576092768241-dec231879fc3?auto=format&fit=crop&w=600&q=80',
    stock: 35,
    badge: 'Orgánico',
    rating: 4.9,
    presentation: 'Bolsa kraft hermética y compostable de 100g',
    ingredients: 'Matricaria chamomilla, Passiflora incarnata, Melissa officinalis, Citrus aurantium.',
    benefits: ['Calma digestiva y mental', 'Libre de teína/cafeína', 'Aroma floral envolvente'],
    usage: 'Infusionar 1 cucharada en 250ml de agua a 90°C durante 6 a 8 minutos tapado.'
  },
  {
    id: 'np-05',
    name: 'Shampoo Sólido de Romero y Ortiga',
    description: 'Fórmula sin sulfatos ni siliconas para estimular el crecimiento, regular el sebo y fortalecer la raíz capilar.',
    category: 'Cuidado personal',
    priceBs: 380.00,
    priceUsd: 10.41,
    image: 'https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=600&q=80',
    stock: 28,
    badge: 'Zero Waste',
    rating: 4.7,
    presentation: 'Barra sólida artesanal de 90g en estuche ecológico',
    ingredients: 'Sodium Cocoyl Isethionate (de coco), infusión concentrada de romero, polvo de ortiga verde, aceite de jojoba.',
    benefits: ['Fortalece el folículo piloso', 'Dura hasta 60 lavados', 'Biodegradable y libre de plástico'],
    usage: 'Frotar la pastilla sobre el cabello húmedo hasta generar espuma cremosa, masajear el cuero cabelludo y enjuagar.'
  },
  {
    id: 'np-06',
    name: 'Espirulina & Chlorella Orgánica en Polvo',
    description: 'Superalimento verde desintoxicante rico en clorofila, proteínas vegetales biodisponibles y hierro.',
    category: 'Suplementos',
    priceBs: 580.00,
    priceUsd: 15.89,
    image: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&w=600&q=80',
    stock: 20,
    badge: 'Superfood',
    rating: 4.8,
    presentation: 'Doypack resellable de 200g',
    ingredients: 'Spirulina platensis 50% y Chlorella vulgaris de pared celular rota 50% certificadas orgánicas.',
    benefits: ['Depuración celular de metales pesados', 'Energía limpia sin cafeína', 'Aporte vegetal de B12 y hierro'],
    usage: 'Mezclar 1 cucharadita (5g) en batidos verdes, jugos de frutas o agua tibia matutina.'
  },
  {
    id: 'np-07',
    name: 'Aceite Esencial de Árbol de Té (Tea Tree)',
    description: 'Purificante botánico antibacteriano de máxima pureza. Ideal para acné, cutículas y cuidado de la piel.',
    category: 'Aceites esenciales',
    priceBs: 420.00,
    priceUsd: 11.50,
    image: 'https://images.unsplash.com/photo-1601049541289-9b1b7bbbfe19?auto=format&fit=crop&w=600&q=80',
    stock: 30,
    badge: '100% Puro',
    rating: 4.9,
    presentation: 'Frasco ámbar de 15ml',
    ingredients: 'Melaleuca alternifolia 100% puro de origen australiano.',
    benefits: ['Propiedades antisépticas comprobadas', 'Controla imperfecciones en la piel', 'Purifica el aire en difusor'],
    usage: 'Aplicar 1 gota puntual sobre imperfección o añadir al champú / limpiador facial habitual.'
  },
  {
    id: 'np-08',
    name: 'Bálsamo Labial de Caléndula y Cera de Abeja',
    description: 'Reparador intensivo para labios secos o agrietados con extracto de caléndula cultivada orgánicamente.',
    category: 'Cosmética natural',
    priceBs: 190.00,
    priceUsd: 5.20,
    image: 'https://images.unsplash.com/photo-1599305090598-fe179d501227?auto=format&fit=crop&w=600&q=80',
    stock: 50,
    badge: 'Artesanal',
    rating: 4.9,
    presentation: 'Tubo ecológico de cartón biodegradable de 10g',
    ingredients: 'Macerado de flor de caléndula en aceite de oliva virgen extra, cera pura de abeja, manteca de karité.',
    benefits: ['Hidratación prolongada', 'Protección contra el viento y frío', 'Fórmula 100% comestible y segura'],
    usage: 'Aplicar generosamente sobre los labios según necesidad a lo largo del día.'
  },
  {
    id: 'np-09',
    name: 'Té Verde Matcha Ceremonial de Uji',
    description: 'Primer brote cosechado en sombra y molido en piedra. Gran concentración de antioxidantes L-teanina y EGCG.',
    category: 'Tés e infusiones',
    priceBs: 790.00,
    priceUsd: 21.64,
    image: 'https://images.unsplash.com/photo-1536256263959-770b48d82b0a?auto=format&fit=crop&w=600&q=80',
    stock: 14,
    badge: 'Grado Ceremonial',
    rating: 5.0,
    presentation: 'Lata metálica hermética de 50g sellada al vacío',
    ingredients: 'Camellia sinensis orgánica 100% grado ceremonial origen Kioto/Uji.',
    benefits: ['Concentración mental sostenida sin taquicardia', 'Acelerador metabólico suave', 'Poder antioxidante superior'],
    usage: 'Batir 1-2g en 70ml de agua a 75°C con chasen (batidor de bambú) hasta lograr espuma densa.'
  },
  {
    id: 'np-10',
    name: 'Gel Puro de Aloe Vera 99% con Manzanilla',
    description: 'Hidratante refrescante inmediato para después del sol, irritaciones cutáneas o base de sérums ligeros.',
    category: 'Cuidado personal',
    priceBs: 350.00,
    priceUsd: 9.58,
    image: 'https://images.unsplash.com/photo-1598440947619-2c35fc9aa908?auto=format&fit=crop&w=600&q=80',
    stock: 32,
    badge: '99% Puro',
    rating: 4.8,
    presentation: 'Envase dispensador de 250ml',
    ingredients: 'Jugo de hoja de Aloe Barbadensis Miller ecológico 99%, extracto hidroglicerinado de Chamomilla recutita.',
    benefits: ['Alivio instantáneo post-solar', 'No comedogénico ni pegajoso', 'Calma rojeces e irritaciones'],
    usage: 'Aplicar suavemente sobre la piel limpia las veces que sea necesario.'
  },
  {
    id: 'np-11',
    name: 'Extracto de Ashwagandha KSM-66',
    description: 'Adaptógeno ayurvédico estandarizado al 5% de withanólidos. Regula los niveles de cortisol y el estrés crónico.',
    category: 'Suplementos',
    priceBs: 690.00,
    priceUsd: 18.90,
    image: 'https://images.unsplash.com/photo-1584017911766-d451b3d0e843?auto=format&fit=crop&w=600&q=80',
    stock: 22,
    badge: 'Adaptógeno',
    rating: 4.9,
    presentation: 'Frasco de 60 cápsulas veganas',
    ingredients: 'Extracto de raíz de Withania somnifera KSM-66® (600mg por dosis), extracto de pimienta negra BioPerine® (5mg).',
    benefits: ['Equilibrio hormonal y adrenal', 'Resistencia al agotamiento mental', 'Mejora del vigor y la serenidad'],
    usage: '1 cápsula por la mañana y 1 por la noche junto con las comidas.'
  },
  {
    id: 'np-12',
    name: 'Jabón Botánico de Avena, Miel y Caléndula',
    description: 'Saponificado en frío durante 6 semanas con aceites vegetales nobles. Limpieza ultrasuave para pieles sensibles.',
    category: 'Cuidado personal',
    priceBs: 220.00,
    priceUsd: 6.02,
    image: 'https://images.unsplash.com/photo-1600857544200-b2f666a9a2ec?auto=format&fit=crop&w=600&q=80',
    stock: 40,
    badge: 'Artesanal',
    rating: 4.9,
    presentation: 'Pastilla de 120g envuelta en papel reciclado',
    ingredients: 'Aceite de oliva virgen extra saponificado, aceite de coco, avena coloidal, miel cruda de monte, pétalos de caléndula.',
    benefits: ['Respeta el manto lipídico natural', 'Espuma cremosa libre de detergentes sintéticos', 'Aroma cálido a miel pura'],
    usage: 'Generar espuma entre las manos y lavar rostro o cuerpo con agua tibia.'
  }
];

export const CATEGORIES = [
  'Todos',
  'Suplementos',
  'Aceites esenciales',
  'Cosmética natural',
  'Tés e infusiones',
  'Cuidado personal'
] as const;
